/// Flutter icons IconPack
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPack
///      fonts:
///       - asset: fonts/IconPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';

  static const IconData carret_backward = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData carret_down = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData carret_foward = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData carret_up = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData color = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData dots_horizontal = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData dots_vertical = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData effort_icon = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData feedback = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData habit = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData login = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData menu_line = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData nutrition = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData sleep = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData stars = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData bulb = const IconData(0xe83e, fontFamily: _kFontFam);
}
